### ISSUE TITLE
Clarification of delta parameter used in FIF function

### ISSUE THREAD

**Issue by JEMH** [EmanuelePapini/FIF#2]
In the paper „Numerical Analysis for Iterative Filtering…“ by Antonio Cicone and Haomin Zhou, a delta parameter is used as in the stopping criterion to bound an l_2 norm.

I was expecting the delta parameter that is passed to the FIF function of FIF_v3_4 to be the same delta.

However, in the FIF function, the delta parameter is compared to the ratio of two sums of squares rather than the ratios of l_2 norms.

To be consistent shouldn‘t
EITHER
  the calculated residual should be compared to delta*delta
OR
  the residual should calculate the ratio of the l_2 norms?

**Comment by EmanuelePapini** [comment]
The delta parameter in the FIF algorithm is equivalent to that of the paper you cited, however it does not have the same definition. For historical reasons, the delta used in the algorithm follows the same definition of the delta used in the EMD algorithm that you can find in Equation 5.5 in the original publication about the EMD "The empirical mode decomposition and the Hilbert spectrum for nonlinear and non-stationary time series analysis" (Huang et al. 1998, DOI:10.1098/rspa.1998.0193)
